#!/bin/bash

# Comments: Simple

# Comments: Ignore remainder of line
/usr/bin/valgrind -q ./proj3 <<END
Did you read % this file to see what it tests?  Did you read
the final specification?
END

echo -----

# Comments: Ignore leading blanks/tabs on following line
/usr/bin/valgrind -q ./proj3 <<END
Did you read % this file to see what it tests?  Did you read
	     the final specification?
END
