#!/bin/bash

# Escaped characters: Simple

TESTS=/c/cs323/proj3/tests

/usr/bin/valgrind -q ./proj3 < $TESTS/t14x

echo -----

/usr/bin/valgrind -q ./proj3   $TESTS/t14x

echo -----

/usr/bin/valgrind -q ./proj3 <<'END'
\def{escape}{To escape a # precede it by a backslash}
\escape{\\}
\escape{\{}
\escape{\}}
END
